export const ALUNOS = [
  { id: 1, nome: 'Eduardo Tavares', idade: 18, curso: 'Ciência da Computação' },
  { id: 2, nome: 'Aline Barreto', idade: 24, curso: 'Medicina' },
  { id: 3, nome: 'Victor Carvalho', idade: 21, curso: 'Engenharia Mecânica' },
  { id: 4, nome: 'Sofia Monteiro', idade: 20, curso: 'Design Gráfico' },
  { id: 5, nome: 'Henrique Castro', idade: 22, curso: 'Geografia' },
  { id: 6, nome: 'Letícia Farias', idade: 23, curso: 'Farmácia' },
  { id: 7, nome: 'Mateus Rocha', idade: 19, curso: 'Ciências Contábeis' },
  { id: 8, nome: 'Camila Duarte', idade: 25, curso: 'Enfermagem' },
  { id: 9, nome: 'Igor Mendes', idade: 20, curso: 'Publicidade e Propaganda' },
  { id: 10, nome: 'Natália Borges', idade: 22, curso: 'Matemática' },
  { id: 11, nome: 'André Vasconcelos', idade: 21, curso: 'Fisioterapia' },
  { id: 12, nome: 'Milena Souza', idade: 24, curso: 'Oceanografia' },
  { id: 13, nome: 'Rafael Guimarães', idade: 19, curso: 'Engenharia de Produção' },
  { id: 14, nome: 'Brenda Lopes', idade: 20, curso: 'Teatro' },
  { id: 15, nome: 'Caio Santana', idade: 23, curso: 'Economia' },
  { id: 16, nome: 'Jéssica Martins', idade: 18, curso: 'Antropologia' },
  { id: 17, nome: 'Pedro Henrique', idade: 25, curso: 'Engenharia Ambiental' },
  { id: 18, nome: 'Luana Rezende', idade: 20, curso: 'Serviço Social' },
  { id: 19, nome: 'Fernando Queiroz', idade: 21, curso: 'Astronomia' },
  { id: 20, nome: 'Talita Lima', idade: 22, curso: 'Moda' },
];
